spring:
  application:
    name: "CosmosConnect Local"
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/local
    username: user
    password: pw
jwt:
  key: "Lo16Oo15M150c13mTlgdJUxj7ZlaBdteZsbkUClLN2I"
sso:
  google:
    clientId: "1000232559307-n4gnukqqpcmiobetmhjn4t98ojvesnui.apps.googleusercontent.com"